config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :home
  resources :payments do
    collection do
      get 'success'
      get 'canceled'
      get 'ipn'
      get 'completed'
      get 'failed'
    end
  end

end

app/models/payment.rb
class Payment < ActiveRecord::Base

  def self.checkout_recurring_paypal(success_path, cancel_path, ipn_path)
    ppr = PayPal::Recurring.new({
                                    :return_url   => APP_URL + success_path,
                                    :cancel_url   => APP_URL + cancel_path,
                                    :ipn_url      => APP_URL + ipn_path,
                                    :description  => "Awesome - Monthly HeroTalkies Subscription",
                                    :amount       => "7.00",
                                    :currency     => "USD"
                                })

    response = ppr.checkout
  end

  def self.get_checkout_details(token)
    ppr = PayPal::Recurring.new(:token => token)
    response = ppr.checkout_details

    # Puts for details
    p response.email
    p response.first_name
    p response.last_name
    p response.status
    p response.trust # Gave All Details

    response
  end

  def self.request_payment(token, payer_id)
    ppr = PayPal::Recurring.new({
                                    :token       => token,
                                    :payer_id    => payer_id,
                                    :amount      => "7.00",
                                    :description => "Awesome - Monthly HeroTalkies Subscription"
                                })
    response = ppr.request_payment
  end

  def self.create_recurring_profile(token)
    ppr = PayPal::Recurring.new({
                                    :amount      => "7.00",
                                    :currency    => "USD",
                                    :description => "Awesome - Monthly HeroTalkies Subscription",
                                    :ipn_url     => "http://localhost:3000/payments/ipn",
                                    :frequency   => 1,
                                    :token       => token,
                                    :period      => :monthly,
                                    :reference   => "#{Time.now.to_i}",
                                    :payer_id    => "WTTS5KC2T46YU",
                                    :start_at    => Time.now,
                                    :failed      => 1,
                                    :outstanding => :next_billing
                                })

    response = ppr.create_recurring_profile
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def index
    response = Payment.checkout_recurring_paypal(success_payments_path, canceled_payments_path, ipn_payments_path)

    if response.valid?
      puts response.checkout_url
      redirect_to response.checkout_url
    else
      flash[:errors] = response.errors[0][:messages]
      redirect_to failed_payments_path
    end
  end

  # User Authorize the payment Request
  def success
    token = params[:token]
    payer_id = params[:PayerID]

    # Get Checkout Details
    Payment.get_checkout_details(token)

    response = Payment.request_payment(token, payer_id)

    if response.approved? && response.completed?
      # Create Recurring Profile
      response = Payment.create_recurring_profile(token)
      puts response.profile_id

      Payment.create(:user_id => 1, :token => token, :profile_id => response.profile_id)

      return redirect_to completed_payments_path
    else
      messages = response.errors[0][:messages]
      flash[:errors] = messages
      return redirect_to failed_payments_path
    end
  end

  # User Reject the payment Request
  def canceled
    p params
    #TODO: we can update this detail while logged in user Canceled payment
    redirect_to root_path
  end

  def ipn
    p params
    #TODO: Have to check
    redirect_to root_path
  end

  # After successfully completed payment
  def completed

  end

  def failed
    p flash[:errors]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/home/index.html.erb
<%= link_to(image_tag("express-checkout-hero.png"), payments_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HeroPaypal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/payments/completed.html.erb
<html>
<head>
  <title>JW Player-HLS Adaptive</title>
  <script src="http://jwpsrv.com/library/AcswGg5eEeSEFyIACtqXBA.js"></script>
</head>
<body style="background: #333;">
<div id="playerContainer">We are loading the Player</div>
<script type="text/javascript">
    jwplayer("playerContainer").setup({
        image: "http://d382j8j5g7zlk1.cloudfront.net/images/overlays/Madras.png",
        file: "http://dn4uhxtx5uwq5.cloudfront.net/madras_v1/index.m3u8",
        tracks: [
            { file: 'http://s3-ap-southeast-1.amazonaws.com/ht-tamil-movies-v1/madras_v1/madras_v1.vtt', kind: 'captions', label: "English" },
        ],
        width: 930,
        height: 523,
        skin: "five",
        cast:{
            appid:"4E28EE1C",
            loadscreen:"http://d382j8j5g7zlk1.cloudfront.net/images/overlays/Madras.png",
            endscreen:"http://d382j8j5g7zlk1.cloudfront.net/images/overlays/Madras.png",
            logo:"https://s3-ap-southeast-1.amazonaws.com/herotalkies-assets/images/logo.png",
            railcolor:"#f14833"
        }
    });
</script>
</body>
</html>

app/views/payments/failed.html.erb
<% flash[:errors].each do |error| %>
    <%= error %>,
<% end %>